language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      jdk: openjdk8

# For maven projects, the default installation phase can be skipped
install: true

cache:
  directories:
    - $HOME/.m2/repository

script: mvn --version && mvn clean test -B 
